export const questions = [
    {
      id: '1',
      question: 'What is the highest Mountain on earth?',
      answer1: 'Mount Everest',
      answer2: 'K2',
      answer3: 'Zugspitze',
      answer4: 'Lhotse',
      solution: 1,
      category: 'general',
      imageUrl: 'none',
      subject: 'Mount Everest',
    },
    {
        id: '2',
        question: 'When did the 2nd world war start?',
        answer1: 'January 1, 1938',
        answer2: 'August 17, 1942',
        answer3: 'September 1, 1939',
        answer4: 'August 5, 1938',
        solution: 3,
        category: 'general',
        imageUrl: 'https://cdn.jsdelivr.net/gh/a-static/ask/2nd-world-war.jpg',
        subject: '2nd world war',
    },
    {
      id: '3',
      question: 'Who was the first president of the USA?',
      answer1: 'Franklin D. Roosevelt',
      answer2: 'John F. Kennedy',
      answer3: 'John Tyler',
      answer4: 'George Washington',
      solution: 4,
      category: 'general',
      imageUrl: 'https://cdn.jsdelivr.net/gh/a-static/ask/2nd-world-war.jpg',
      subject: '2nd world war',
  },
    {
      id: '4',
      name: 'Darth Vader',
      height: '202',
      mass: '136',
      hair_color: 'none',
      skin_color: 'white',
      eye_color: 'yellow',
      gender: 'male',
    },
    {
      id: '5',
      name: 'Leia Organa',
      height: '150',
      mass: '49',
      hair_color: 'brown',
      skin_color: 'light',
      eye_color: 'brown',
      gender: 'female',
    },
    {
      id: '6',
      name: 'Owen Lars',
      height: '178',
      mass: '120',
      hair_color: 'brown, grey',
      skin_color: 'light',
      eye_color: 'blue',
      gender: 'male',
    },
    {
      id: '7',
      name: 'Beru Whitesun lars',
      height: '165',
      mass: '75',
      hair_color: 'brown',
      skin_color: 'light',
      eye_color: 'blue',
      gender: 'female',
    },
    {
      id: '8',
      name: 'R5-D4',
      height: '97',
      mass: '32',
      hair_color: 'n/a',
      skin_color: 'white, red',
      eye_color: 'red',
      gender: 'n/a',
    },
    {
      id: '9',
      name: 'Biggs Darklighter',
      height: '183',
      mass: '84',
      hair_color: 'black',
      skin_color: 'light',
      eye_color: 'brown',
      gender: 'male',
    },
    {
      id: '10',
      name: 'Obi-Wan Kenobi',
      height: '182',
      mass: '77',
      hair_color: 'auburn, white',
      skin_color: 'fair',
      eye_color: 'blue-gray',
      gender: 'male',
    },
  ]