export const questions = [
  {
    id: "1",
    question: "What is the highest Mountain on earth?",
    answer1: "Mount Everest",
    answer2: "K2",
    answer3: "Zugspitze",
    answer4: "Lhotse",
    solution: 1,
    category: "general",
    imageUrl: "none",
    subject: "Mount Everest",
  },
  {
    id: "2",
    question: "When did the 2nd world war start?",
    answer1: "January 1, 1938",
    answer2: "August 17, 1942",
    answer3: "September 1, 1939",
    answer4: "August 5, 1938",
    solution: 3,
    category: "history",
    imageUrl: "https://cdn.jsdelivr.net/gh/a-static/ask/2nd-world-war.jpg",
    subject: "2nd world war",
  },
  {
    id: "3",
    question: "Who was the first president of the USA?",
    answer1: "Franklin D. Roosevelt",
    answer2: "John F. Kennedy",
    answer3: "John Tyler",
    answer4: "George Washington",
    solution: 4,
    category: "history",
    imageUrl: "none",
    subject: "first president of the United States",
  },
  {
    id: "4",
    question: "How tall is the Eiffel Tower in Paris?",
    answer1: "93m",
    answer2: "483m",
    answer3: "324m",
    answer4: "111m",
    solution: 3,
    category: "general",
    imageUrl: "none",
    subject: "height of Eiffel Tower",
  },
  {
    id: "5",
    question: "What does MS stand for in front of ship names?",
    answer1: "Ms. (because it's female)",
    answer2: "Mediterranean Sea Cruise",
    answer3: "Motor Ship",
    answer4: "Mare Scala",
    solution: 3,
    category: "general",
    imageUrl: "none",
    subject: "MS in ship names",
  },
  {
    id: "6",
    question: "How fast is speed of light?",
    answer1: "≈ 300 000 000 m/s",
    answer2: "≈ 5 000 m/s",
    answer3: "≈ 66 000 000 m/s",
    answer4: "≈ 200 000 m/s",
    solution: 1,
    category: "general",
    imageUrl: "none",
    subject: "speed of light",
  },
];
