export const questions = [
  {
    id: "1",
    question: "What is the highest Mountain on earth?",
    answer1: "Mount Everest",
    answer2: "K2",
    answer3: "Zugspitze",
    answer4: "Lhotse",
    solution: 1,
    category: "general",
    imageUrl: "none",
    subject: "Mount Everest",
  },
  {
    id: "2",
    question: "When did the 2nd world war start?",
    answer1: "January 1, 1938",
    answer2: "August 17, 1942",
    answer3: "September 1, 1939",
    answer4: "August 5, 1938",
    solution: 3,
    category: "history",
    imageUrl: "https://cdn.jsdelivr.net/gh/a-static/ask/2nd-world-war.jpg",
    subject: "2nd world war",
  },
  {
    id: "3",
    question: "Who was the first president of the USA?",
    answer1: "Franklin D. Roosevelt",
    answer2: "John F. Kennedy",
    answer3: "John Tyler",
    answer4: "George Washington",
    solution: 4,
    category: "history",
    imageUrl: "none",
    subject: "first president of the United States",
  },
  {
    id: "4",
    question: "How tall is the Eiffel Tower in Paris?",
    answer1: "93m",
    answer2: "483m",
    answer3: "324m",
    answer4: "111m",
    solution: 3,
    category: "general",
    imageUrl: "none",
    subject: "height of Eiffel Tower",
  },
  {
    id: "5",
    question: "What does MS stand for in front of ship names?",
    answer1: "Ms. (because it's female)",
    answer2: "Mediterranean Sea Cruise",
    answer3: "Motor Ship",
    answer4: "Mare Scala",
    solution: 3,
    category: "general",
    imageUrl: "none",
    subject: "MS in ship names",
  },
  {
    id: "6",
    question: "How fast is speed of light?",
    answer1: "≈ 300 000 000 m/s",
    answer2: "≈ 5 000 m/s",
    answer3: "≈ 66 000 000 m/s",
    answer4: "≈ 200 000 m/s",
    solution: 1,
    category: "general",
    imageUrl: "none",
    subject: "speed of light",
  },
  {
    id: "7",
    question: "How many continents are there? (Largest model)",
    answer1: "Five",
    answer2: "Six",
    answer3: "Seven",
    answer4: "Eight",
    solution: 3,
    category: "general",
    imageUrl: "none",
    subject: "amount of continents",
  },
  {
    id: "8",
    question: "How tall is Mount Everest?",
    answer1: "4 083m",
    answer2: "8 849m",
    answer3: "10 447m",
    answer4: "13 589m",
    solution: 2,
    category: "general",
    imageUrl: "none",
    subject: "height of Mount Everest",
  },
  {
    id: "9",
    question: "What does “www” stand for in a website browser?",
    answer1: "What, When, Where",
    answer2: "Why, Why, Why",
    answer3: "William Wayne Wackerman",
    answer4: "World Wide Web",
    solution: 4,
    category: "general",
    imageUrl: "none",
    subject: "world wide web",
  },
  {
    id: "10",
    question: "How long is an Olympic swimming pool?",
    answer1: "20m",
    answer2: "25m",
    answer3: "45m",
    answer4: "50m",
    solution: 2,
    category: "general",
    imageUrl: "none",
    subject: "length of Olympic swimming pool",
  },
  {
    id: "11",
    question: "What geometric shape is generally used for stop signs?",
    answer1: "Octagon",
    answer2: "Hectagon",
    answer3: "Rectangle",
    answer4: "Circle",
    solution: 1,
    category: "general",
    imageUrl: "none",
    subject: "length of Olympic swimming pool",
  },
  {
    id: "12",
    question: "What is 'cynophobia'?",
    answer1: "Fear of daylight",
    answer2: "Fear of tight spaces",
    answer3: "Fear of dogs",
    answer4: "Fear of loud music",
    solution: 3,
    category: "general",
    imageUrl: "none",
    subject: "length of Olympic swimming pool",
  }
];
